### ISSUE TITLE
Consider abstract bluetooth functionality

### ISSUE THREAD

**Issue by archi** [sabas1080/PokemonGODIY#1]
Hi, do you plan to support just a single bluetooth lib? Or could you maybe use some kind of abstraction layer?

I am interested in using a LinkIt One for emulating the Go Plus device. But their API is different from yours:
http://labs.mediatek.com/site/global/developer_tools/mediatek_linkit/api_references/Lib_Bluetooth.gsp

In case you don't know that device: It's compatible with the Arduino SDK, but powered by a Mediatek ARM SoC, along with GPRS, GPS, Bluetooth, WiFI,... (IoT dev platform). But I think this suggestion holds for any BT-enabled Arduino-SDK-compatible device.

But if not, that's fine too ;)

**Comment by sabas1080** [comment]
Hi

Find a universal library is difficult, but the project is open to use different platforms , once we found the protocol are sure that would work on any platform

Welcome to collaborate en hackaday.io https://hackaday.io/project/12680-pokemon-go-plus-diy

**Comment by jehy** [comment]
@archi this project wasn't even started, that' just a pretty useless draft.
